version: '3.8'
services:
  webhook:
    image: webhook
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5030:80"
    privileged: true
    environment:
      - WEBHOOK_SECRET