name: publish
on: [push]
jobs:
    publish-docker-image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Login to Github Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          run: |
            REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
            docker build . -t ghcr.io/$REPO_LOWER/webhook:latest
            docker run -d -p 5030:80 ghcr.io/$REPO_LOWER/webhook:latest
            docker push ghcr.io/$REPO_LOWER/webhook:latest